// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using teste.Data;

namespace teste.Data.Migrations
{
    [DbContext(typeof(Teste))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("teste.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Fotografia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("RegisterTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("teste.Models.Bebidas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imagem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Preco")
                        .HasColumnType("real");

                    b.Property<string>("Stock")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Bebidas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = " MATEUS ROSÉ é um vinho leve, fresco, jovem e ligeiramente «pétillant»",
                            Nome = "Vinho Rose Mateus",
                            Preco = 20f,
                            Stock = "Sim"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "É vinificado pelo método tradicional do vinho do Porto.",
                            Nome = "Vinho do Porto Ferreira",
                            Preco = 30f,
                            Stock = "Sim"
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Vinho Moscatel de Setúbal",
                            Nome = "Veritas Moscatel",
                            Preco = 10f,
                            Stock = "Sim"
                        },
                        new
                        {
                            Id = 4,
                            Descricao = "Grant’s é um whisky extraordinário e um dos mais complexos produzidos na Escócia.",
                            Nome = "Grants Whisky",
                            Preco = 15f,
                            Stock = "Sim"
                        },
                        new
                        {
                            Id = 5,
                            Descricao = "Cîroc Vodka é uma marca de vodca eau-de-vie de luxo, fabricada com uvas da região Carântono-Marítimo, da França",
                            Nome = "Ciroc Vodka",
                            Preco = 30f,
                            Stock = "Sim"
                        },
                        new
                        {
                            Id = 6,
                            Descricao = "Nada bate um original, e Malibu não é apenas o original, é o mais vendido rum do Caribe com sabor natural de coco ",
                            Nome = "Malibu Rum",
                            Preco = 15f,
                            Stock = "Sim"
                        },
                        new
                        {
                            Id = 7,
                            Descricao = "Cachaça, o sabor e aroma perfeito da original caipirinha brasileira.",
                            Nome = "Cachaça 51",
                            Preco = 11f,
                            Stock = "Sim"
                        },
                        new
                        {
                            Id = 8,
                            Descricao = "Moet & Chandon, um champanhe de estilo único e elegante.",
                            Nome = "Moet&Chandon",
                            Preco = 50f,
                            Stock = "Sim"
                        },
                        new
                        {
                            Id = 9,
                            Descricao = "O sabor autêntico. Super Bock Original é a única cerveja portuguesa com 37 medalhas de ouro consecutivas",
                            Nome = "Super Bock Pack15",
                            Preco = 7f,
                            Stock = "Sim"
                        });
                });

            modelBuilder.Entity("teste.Models.Clientes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Contacto")
                        .HasMaxLength(11)
                        .HasColumnType("int");

                    b.Property<DateTime>("Datanasc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Fotografia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Contacto = 937492122,
                            Datanasc = new DateTime(1995, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "pr@pr.com",
                            Fotografia = "noUser.png",
                            Nome = "Pedro Rafael"
                        },
                        new
                        {
                            Id = 2,
                            Contacto = 920562956,
                            Datanasc = new DateTime(1994, 12, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jv@jv.com",
                            Fotografia = "noUser.png",
                            Nome = "Jose Vieira"
                        },
                        new
                        {
                            Id = 3,
                            Contacto = 914659935,
                            Datanasc = new DateTime(1999, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ms@ms.com",
                            Fotografia = "noUser.png",
                            Nome = "Maria Silva"
                        },
                        new
                        {
                            Id = 4,
                            Contacto = 936581003,
                            Datanasc = new DateTime(1990, 8, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "fs@fs.com",
                            Fotografia = "noUser.png",
                            Nome = "Filipe Santos"
                        },
                        new
                        {
                            Id = 5,
                            Contacto = 962813384,
                            Datanasc = new DateTime(1998, 2, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "as@as.com",
                            Fotografia = "noUser.png",
                            Nome = "Ana Sousa"
                        },
                        new
                        {
                            Id = 6,
                            Contacto = 961883421,
                            Datanasc = new DateTime(1985, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "bp@bp.com",
                            Fotografia = "noUser.png",
                            Nome = "Beatriz Pinto"
                        },
                        new
                        {
                            Id = 7,
                            Contacto = 917745362,
                            Datanasc = new DateTime(1978, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "tm@tm.com",
                            Fotografia = "noUser.png",
                            Nome = "Tiago Mendonça"
                        });
                });

            modelBuilder.Entity("teste.Models.Reservas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BebidaFK")
                        .HasColumnType("int");

                    b.Property<int>("ClienteFK")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataEntrega")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataReserva")
                        .HasColumnType("datetime2");

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BebidaFK");

                    b.HasIndex("ClienteFK");

                    b.ToTable("Reservas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BebidaFK = 1,
                            ClienteFK = 1,
                            DataEntrega = new DateTime(2022, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataReserva = new DateTime(2021, 9, 19, 3, 35, 30, 744, DateTimeKind.Local).AddTicks(8397),
                            Estado = "Entregue",
                            Quantidade = 2
                        },
                        new
                        {
                            Id = 2,
                            BebidaFK = 2,
                            ClienteFK = 2,
                            DataEntrega = new DateTime(2021, 12, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataReserva = new DateTime(2021, 9, 19, 3, 35, 30, 749, DateTimeKind.Local).AddTicks(4317),
                            Estado = "Entregue",
                            Quantidade = 1
                        },
                        new
                        {
                            Id = 3,
                            BebidaFK = 3,
                            ClienteFK = 3,
                            DataEntrega = new DateTime(2022, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataReserva = new DateTime(2021, 9, 19, 3, 35, 30, 749, DateTimeKind.Local).AddTicks(4360),
                            Estado = "Entregue",
                            Quantidade = 1
                        },
                        new
                        {
                            Id = 4,
                            BebidaFK = 4,
                            ClienteFK = 4,
                            DataEntrega = new DateTime(2022, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataReserva = new DateTime(2021, 9, 19, 3, 35, 30, 749, DateTimeKind.Local).AddTicks(4365),
                            Estado = "Entregue",
                            Quantidade = 1
                        },
                        new
                        {
                            Id = 5,
                            BebidaFK = 5,
                            ClienteFK = 5,
                            DataEntrega = new DateTime(2021, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataReserva = new DateTime(2021, 9, 19, 3, 35, 30, 749, DateTimeKind.Local).AddTicks(4369),
                            Estado = "Entregue",
                            Quantidade = 5
                        },
                        new
                        {
                            Id = 6,
                            BebidaFK = 6,
                            ClienteFK = 6,
                            DataEntrega = new DateTime(2021, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataReserva = new DateTime(2021, 9, 19, 3, 35, 30, 749, DateTimeKind.Local).AddTicks(4373),
                            Estado = "Entregue",
                            Quantidade = 2
                        },
                        new
                        {
                            Id = 7,
                            BebidaFK = 7,
                            ClienteFK = 7,
                            DataEntrega = new DateTime(2022, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataReserva = new DateTime(2021, 9, 19, 3, 35, 30, 749, DateTimeKind.Local).AddTicks(4377),
                            Estado = "Entregue",
                            Quantidade = 3
                        },
                        new
                        {
                            Id = 8,
                            BebidaFK = 8,
                            ClienteFK = 3,
                            DataEntrega = new DateTime(2022, 6, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataReserva = new DateTime(2021, 9, 19, 3, 35, 30, 749, DateTimeKind.Local).AddTicks(4380),
                            Estado = "Entregue",
                            Quantidade = 1
                        },
                        new
                        {
                            Id = 11,
                            BebidaFK = 9,
                            ClienteFK = 2,
                            DataEntrega = new DateTime(2022, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataReserva = new DateTime(2021, 9, 19, 3, 35, 30, 749, DateTimeKind.Local).AddTicks(4384),
                            Estado = "Entregue",
                            Quantidade = 4
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("teste.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("teste.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("teste.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("teste.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("teste.Models.Reservas", b =>
                {
                    b.HasOne("teste.Models.Bebidas", "Bebida")
                        .WithMany("ListaDeReservas")
                        .HasForeignKey("BebidaFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("teste.Models.Clientes", "Cliente")
                        .WithMany("ListaDeReservas")
                        .HasForeignKey("ClienteFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bebida");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("teste.Models.Bebidas", b =>
                {
                    b.Navigation("ListaDeReservas");
                });

            modelBuilder.Entity("teste.Models.Clientes", b =>
                {
                    b.Navigation("ListaDeReservas");
                });
#pragma warning restore 612, 618
        }
    }
}
